init repository
White-AK111/shortener pull request #1
Opened 2021-12-11 11:06 UTC by White-AK111

2021-12-12 19:52 UTC, v-lozhkin requested changes

2021-12-12 19:52 UTC, v-lozhkin commented on .idea/.gitignore
> +# Default ignored files
Так ли тут нужна папка .idea?)

2021-12-12 19:52 UTC, v-lozhkin commented on .github/workflows/pre-commit.yml
> +name: pre-commit
Чем обусловлено такое название для экшена?)

2021-12-12 19:52 UTC, v-lozhkin commented on .github/workflows/pre-commit.yml
> +      - uses: actions/setup-python@v2
Как планируете использовать питон?

2021-12-12 19:52 UTC, v-lozhkin commented on .github/workflows/pre-commit.yml
> +      - uses: pre-commit/action@v2.0.3
Видимо, питон нужен сюда? 
Я пока не уверен, зачем вам этот степ. Предположу, что вас так учил предыдущий преподаватель? 
Насколько я понял, этот проект признан устаревшим разработчиками (https://github.com/pre-commit/action), и вы не единственный, кто столкнулся с этой проблемой (https://github.com/pre-commit/action/issues/131). 
Подскажите, какой цели вы здесь пытаетесь добиться, и возможно, мыы найдем для нее новый путь?)

2021-12-13 05:18 UTC, White-AK111 commented on .idea/.gitignore
> +# Default ignored files
Если я добавляю её в гитигнор, то при создании новой ветки у меня начинает корячить рабочее пространство GoLand'а, как это победить я так и не смог найти.
Поэтому для нормальной работы с ветками в IDE, да, мне нужна )

2021-12-13 05:22 UTC, White-AK111 commented on .github/workflows/pre-commit.yml
> +name: pre-commit
Из примера https://github.com/pre-commit/action, его использование хуков в Github Actions нам рекомендовали на курсе best practices Go.

2021-12-13 05:25 UTC, White-AK111 commented on .github/workflows/pre-commit.yml
> +      - uses: actions/setup-python@v2
https://pre-commit.com/#install эта утилита для хуков использует питон.

2021-12-13 05:36 UTC, White-AK111 commented on .github/workflows/pre-commit.yml
> +      - uses: pre-commit/action@v2.0.3
Да, всё верно.
Уже починили, заработало на GitHub Actions.
Цель: запуск в GitHub Actions pre-commit хука при PR, эта же утилита используется при коммите в локальной репе. Запускает утилиту pre-commit беря конфигурацию из файла .pre-commit-config.yaml.
Сейчас там настроено что перед коммитом (локально) или pr (удалённо) утилита запускает проверки на:
hooks:
        -   id: check-yaml - проверка формата файлов конфигурации
        -   id: end-of-file-fixer - проверка файлов на корректный символ окончания
        -   id: trailing-whitespace - убирает лишние пробелы в файлах
hooks:
        -   id: go-imports - запускает проверку imports 
        -   id: golangci-lint - запускает линтеры, беря настройки из .golangci.yml 
        -   id: go-unit-tests - запускает unit тесты
      
Повторюсь, так нас научили настраивать хуки на курсе best practices Go.
То что он на maintenance-only видел, но как настроить новую версию не осознал, она как то хитро ставится в сам GitHub.
Предлагаю разобрать на консультации альтернативный вариант настройки хуков для CI.

2021-12-14 07:55 UTC, v-lozhkin commented on .idea/.gitignore
> +# Default ignored files
Кажется, вы что-то делаете не так. 
Гиту эта папка совсем не нужна, в отличии от вашей IDE. 
Если вы не удалите эту папку с компьютера, но удалите из файлов, отслеживаемых гитом, все должно быть хорошо. 
Просто, если вы планируете использовать этот проект в своем портфолио - наличие в нем папки .idea - сразу бросается в глаза как красный флаг :)

2021-12-14 12:56 UTC, White-AK111 commented on .idea/.gitignore
> +# Default ignored files
все должно быть хорошо - но нет, не всё хорошо
ок, добавлю в gitignor и буду на каждой новой ветке плясать с бубном, раз это так принципиально

2021-12-19 03:40 UTC, merged